// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPadEOKOEjjMKjGPM-CIIw-3cDcFq0jXA',
    appId: '1:1081926746625:web:f87789dc7876078f023600',
    messagingSenderId: '1081926746625',
    projectId: 'curvyfit-53dba',
    authDomain: 'curvyfit-53dba.firebaseapp.com',
    storageBucket: 'curvyfit-53dba.firebasestorage.app',
    measurementId: 'G-N423QV63BX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjSFzwHzzHvou7o1Yu3PV76jzN9jBHfpg',
    appId: '1:1081926746625:android:5e24a0976a98e585023600',
    messagingSenderId: '1081926746625',
    projectId: 'curvyfit-53dba',
    storageBucket: 'curvyfit-53dba.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAyKgvB18Julomek-dvPye9zJZOSzDaUAc',
    appId: '1:1081926746625:ios:a73a1e94307e0ffb023600',
    messagingSenderId: '1081926746625',
    projectId: 'curvyfit-53dba',
    storageBucket: 'curvyfit-53dba.firebasestorage.app',
    iosClientId: '1081926746625-jetv5moqpmdno8em5n0v8vih7oiqlq35.apps.googleusercontent.com',
    iosBundleId: 'com.example.curvyFit',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDPadEOKOEjjMKjGPM-CIIw-3cDcFq0jXA',
    appId: '1:1081926746625:web:488a2e15f92680c7023600',
    messagingSenderId: '1081926746625',
    projectId: 'curvyfit-53dba',
    authDomain: 'curvyfit-53dba.firebaseapp.com',
    storageBucket: 'curvyfit-53dba.firebasestorage.app',
    measurementId: 'G-E1YJH1R9F8',
  );
}
